# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: estetly
services:
  postgresql:
    image: postgres:16.1
    volumes:
      - ~/postgresql/:/var/lib/postgresql/data/
    # volumes:
    #   - ~/volumes/jhipster/Estetly/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Estetly
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@estetly.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data:
